["作業量: 1-膨大"]
color = "ff6666"
name = "作業量: 1-膨大"
description = "1ファイル変更する程度"

["作業量: 2-多"]
color = "ff8a65"
name = "作業量: 2-多"
description = "数十行変更する程度"

["作業量: 3-中"]
color = "ffd166"
name = "作業量: 3-中"
description = "数行変更する程度"

["作業量: 4-少"]
color = "dce775"
name = "作業量: 4-少"
description = "1行変更する程度"

["作業量: 5-ほぼ無し"]
color = "81c785"
name = "作業量: 5-ほぼ無し"
description = "数文字変更する程度"

["フィードバック: 1-議論"]
color = "ec79a1"
name = "フィードバック: 1-議論"
description = "機能に関する議論"

["フィードバック: 2-質問"]
color = "ec79a1"
name = "フィードバック: 2-質問"
description = "機能に関する質問"

["フィードバック: 3-提案"]
color = "ec79a1"
name = "フィードバック: 3-提案"
description = "機能に関する提案"

["優先度: 1-最優先"]
color = "ff6666"
name = "優先度: 1-最優先"
description = "すぐさま取り組む必要がある程度"

["優先度: 2-高"]
color = "ff8a65"
name = "優先度: 2-高"
description = "早く取り組む必要がある程度"

["優先度: 3-中"]
color = "ffd166"
name = "優先度: 3-中"
description = "なるべく早く取り組む必要がある程度"

["優先度: 4-低"]
color = "dce775"
name = "優先度: 4-低"
description = "いつか取り組む必要がある程度"

["優先度: 5-最低"]
color = "81c785"
name = "優先度: 5-最低"
description = "余裕があれば取り組む程度"

["ステータス: 1-待機中"]
color = "186d86"
name = "ステータス: 1-待機中"
description = "待機中"

["ステータス: 2-作業中"]
color = "1fada2"
name = "ステータス: 2-作業中"
description = "作業中"

["ステータス: 3-作業完了"]
color = "22c373"
name = "ステータス: 3-作業完了"
description = "作業完了"

["ステータス: 4-作業中止"]
color = "376863"
name = "ステータス: 4-作業中止"
description = "作業中止"

["ステータス: 5-重複"]
color = "284f77"
name = "ステータス: 5-重複"
description = "Issueの重複"

["ステータス: 6-保留"]
color = "375f67"
name = "ステータス: 6-保留"
description = "保留"

["タイプ: 1-バグ修正"]
color = "ff6666"
name = "タイプ: 1-バグ修正"
description = "バグ修正"

["タイプ: 2-新機能追加"]
color = "ffdb66"
name = "タイプ: 2-新機能追加"
description = "新機能追加"

["タイプ: 3-改良修正"]
color = "66baff"
name = "タイプ: 3-改良修正"
description = "文法修正など"

["タイプ: 4-最適化"]
color = "669eff"
name = "タイプ: 4-最適化"
description = "処理の高速化、安定化など"

["タイプ: 5-セキュリティ修正"]
color = "ff6666"
name = "タイプ: 5-セキュリティ修正"
description = "セキュリティ問題の修正"
