["1-ステータス: 1-待機中"]
color = "26afd9"
name = "1-ステータス: 1-待機中"
description = "待機中"

["1-ステータス: 2-作業中"]
color = "1fada2"
name = "1-ステータス: 2-作業中"
description = "作業中"

["1-ステータス: 3-作業完了"]
color = "22c373"
name = "1-ステータス: 3-作業完了"
description = "作業完了"

["1-ステータス: 4-作業中止"]
color = "4d807a"
name = "1-ステータス: 4-作業中止"
description = "作業中止"

["1-ステータス: 5-重複"]
color = "336699"
name = "1-ステータス: 5-重複"
description = "Issueの重複"

["1-ステータス: 6-保留"]
color = "4f767d"
name = "1-ステータス: 6-保留"
description = "保留"

["2-タイプ: 1-バグ修正"]
color = "ff6666"
name = "2-タイプ: 1-バグ修正"
description = "バグ修正"

["2-タイプ: 2-新機能追加"]
color = "ffdb66"
name = "2-タイプ: 2-新機能追加"
description = "新機能追加"

["2-タイプ: 3-改良修正"]
color = "66baff"
name = "2-タイプ: 3-改良修正"
description = "文法修正など"

["2-タイプ: 4-最適化"]
color = "669eff"
name = "2-タイプ: 4-最適化"
description = "処理の高速化、安定化など"

["2-タイプ: 5-セキュリティ修正"]
color = "ff6666"
name = "2-タイプ: 5-セキュリティ修正"
description = "セキュリティ問題の修正"

["3-優先度: 1-最優先"]
color = "ff6666"
name = "3-優先度: 1-最優先"
description = "すぐさま取り組む必要がある程度"

["3-優先度: 2-高"]
color = "ff8a65"
name = "3-優先度: 2-高"
description = "早く取り組む必要がある程度"

["3-優先度: 3-中"]
color = "ffd166"
name = "3-優先度: 3-中"
description = "なるべく早く取り組む必要がある程度"

["3-優先度: 4-低"]
color = "dce775"
name = "3-優先度: 4-低"
description = "いつか取り組む必要がある程度"

["3-優先度: 5-最低"]
color = "81c785"
name = "3-優先度: 5-最低"
description = "余裕があれば取り組む程度"

["4-作業量: 1-膨大"]
color = "ff6666"
name = "4-作業量: 1-膨大"
description = "1ファイル変更する程度"

["4-作業量: 2-多"]
color = "ff8a65"
name = "4-作業量: 2-多"
description = "数十行変更する程度"

["4-作業量: 3-中"]
color = "ffd166"
name = "4-作業量: 3-中"
description = "数行変更する程度"

["4-作業量: 4-少"]
color = "dce775"
name = "4-作業量: 4-少"
description = "1行変更する程度"

["4-作業量: 5-ほぼ無し"]
color = "81c785"
name = "4-作業量: 5-ほぼ無し"
description = "数文字変更する程度"

["5-フィードバック: 1-議論"]
color = "ec79a1"
name = "5-フィードバック: 1-議論"
description = "機能に関する議論"

["5-フィードバック: 2-質問"]
color = "ec79a1"
name = "5-フィードバック: 2-質問"
description = "機能に関する質問"

["5-フィードバック: 3-提案"]
color = "ec79a1"
name = "5-フィードバック: 3-提案"
description = "機能に関する提案"
