name: "バグ報告"
description: "バグが発生した際のテンプレート"
title: "Bug: "
labels: ["1-ステータス: 1-待機中"]
assignees: ["Geusen"]


body:
  - type: checkboxes
    attributes:
      label: 0.ラベル付け
      description: ラベルを付け終えたらチェックしてください。
      options:
        - label: ①ステータス  状態を表すラベル(Issue作成時は待機中で良い)
          required: true
        - label: ②タイプ  作業の種別を表すラベル
          required: true
        - label: ③優先度  優先度を表すラベル(任意)
        - label: ④作業量  想定される作業量を表すラベル(任意)

  - type: textarea
    attributes:
      label: 1.概要
      description: >
        バグの概要を記入してください。
      placeholder: >
        例)- news.pyにてpip installでエラー
    validations:
      required: true


  - type: textarea
    attributes:
      label: 2.再現手順、エラー内容等
      description: >
        再現手順やエラーの内容などを記入してください。
      placeholder: >
        - https://github.com/Geusen/Schedule_Bot/actions/runs/3579455799/jobs/6020667956
          -  ```run python```の97行目～
    validations:
      required: true

  - type: textarea
    attributes:
      label: エラーコード(任意)
      description: >
        エラーコードがある場合は記入してください。
      placeholder: >
        ```
          Successfully installed PySocks-1.7.1 async-generator-1.10 attrs-22.1.0 h11-0.14.0 outcome-1.2.0 selenium-4.5.0 sniffio-1.3.0 sortedcontainers-2.4.0 trio-0.22.0 trio-websocket-0.9.2 wsproto-1.2.0
          ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
          ERROR: No matching distribution found for opencv
          Error: Process completed with exit code 1.
        ```

  - type: textarea
    attributes:
      label: 3.関連Issue、Discussions(任意)
      description: >
        関連するIssue、PullRequests、Discussionsがある場合は記入してください。
      placeholder: >
        - #1

  - type: textarea
    attributes:
      label: 4.原因(任意)
      description: >
        原因が分かる場合は記入してください。
      placeholder: >
        - パッケージのバージョン指定ミス

  - type: textarea
    attributes:
      label: 5.修正案(任意)
      description: >
        修正案がある場合は記入してください。
      placeholder: >
        - [ ] ```/.github/workflows/News.yml```の```pip install opencv==4.60.66```を```pip install opencv==4.6.0.66```に変更

  - type: textarea
    attributes:
      label: 6.補足(任意)
      description: >
        他に何かある場合は記入してください。
