name: "バグ報告"
description: "バグが発生した際のテンプレート"
title: "バグ: "
labels: ["1-ステータス: 1-待機中"]
assignees: ["Geusen"]


body:
  - type: markdown
    attributes:
      value: |
        ### 0.ラベル付け
        ①ステータス  状態を表すラベル(Issue作成時は待機中で良い)
        ②タイプ  作業の種別を表すラベル(必須)
        ③優先度  優先度を表すラベル(任意)
        ④作業量  想定される作業量を表すラベル(任意)

  - type: textarea
    attributes:
      label: 1.概要
      description: >
        バグの概要を記入してください。
      placeholder: >
        import pandas as pd
    validations:
      required: true


  - type: textarea
    attributes:
      label: 2.概要
      description: >
        再現手順やエラーの内容を記述してください。
      placeholder: >
        import pandas as pd
    validations:
      required: true

  - type: textarea
    attributes:
      description: >
        エラーコードがある場合は記述してください。
      placeholder: >
        import pandas as pd
