name: grhueiwtghrtwi
on:
  workflow_dispatch:
env:  #環境変数から文字列(パスワードなど)を取得
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.LINE_NOTIFY_13 }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
