name: Configure GitHub labels

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/labels.toml
  push:
    branches:
      - main
    paths:
      - .github/labels.toml
  label:
    types:
      - created
      - edited
      - deleted
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install labels

      # プルリクエスト時 (mainブランチ)
      # push時 (mainブランチ)
      - name: Diff labels
        if: contains(github.event_name, 'pull_request') || contains(github.event_name, 'push')
        run: labels sync --dryrun -f .github/labels.toml
        env:
          LABELS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS_USERNAME: ${{ github.repository_owner }}

      # push時 (mainブランチ)
      - name: Sync labels
        if: contains(github.event_name, 'push')
        run: labels --verbose sync -f .github/labels.toml
        env:
          LABELS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS_USERNAME: ${{ github.repository_owner }}

      - name: Create Pull Request
        if: contains(github.event_name, 'push')
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "既存のラベルから定義ファイルを取得"
          title: "定義ファイルを既存のラベルと同期"
          body: |
            Current definition file and existing labels don't match.
          branch: sync-labels
          branch-suffix: ""

      # 手動変更または手動トリガーを検出時
      - name: Fetch labels
        if: contains(github.event_name, 'label') || contains(github.event_name, 'workflow_dispatch')
        run: labels fetch -f .github/labels.toml
        env:
          LABELS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS_USERNAME: ${{ github.repository_owner }}

      - name: Create Pull Request
        if: contains(github.event_name, 'label') || contains(github.event_name, 'workflow_dispatch')
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "既存のラベルから定義ファイルを取得"
          title: "定義ファイルを既存のラベルと同期"
          body: |
            Current definition file and existing labels don't match.
          branch: sync-labels
          branch-suffix: ""
