name: Local_Images
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ShortcutApp]
env:  # 環境変数から文字列(パスワードなど)を取得
  DICT: ${{ toJson(github.event.client_payload) }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  JSON: ${{ secrets.JSON }}
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY }}
  MISSKEY: ${{ secrets.MISSKEY }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  WEBHOOK: ${{ secrets.WEBHOOK }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: "Asia/Tokyo"
concurrency:  # 同時にworkflowが実行されたらキャンセル
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10    # 10分過ぎたら強制終了
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Run python
        run: |
          echo "::group::pip install --upgrade pip"
          pip install -r ./requirements.txt
          echo "::endgroup::"
          python -B local.py
