name: GitHub_Actions(news)
on:
  #workflow_dispatch:
  schedule:
    - cron: '0 7 1 * *'

env:  #環境変数から文字列(パスワードなど)を取得
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
  WEBHOOK: ${{secrets.WEBHOOK_NEWS}}

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.11.1
          pip install pillow==8.4.0
          pip install tweepy==4.6.0
          python ./news/news.py
