name: GitHub_Actions(news)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

env:  #環境変数から文字列(パスワードなど)を取得
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  WEBHOOK: ${{ secrets.WEBHOOK_NEWS }}
  JSON: ${{ secrets.JSON }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: 'Asia/Tokyo'
concurrency:  # 同時にworkflowが実行されたらキャンセル
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  python:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Run python
        run: |
          echo '::group::pip install --upgrade pip'
          python -m pip install --upgrade pip==23.0
          pip install beautifulsoup4==4.11.2
          pip install gspread==5.7.2
          pip install oauth2client==4.1.3
          pip install pillow==9.4.0
          pip install tweepy==4.12.1
          echo '::endgroup::'
          python -B ./news/news.py
