name: GitHub_Actions(news)
on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 7 * * *'

env:  #環境変数から文字列(パスワードなど)を取得
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
  WEBHOOK: ${{secrets.WEBHOOK_NEWS}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: run python
        run: |
          echo "::group::pip install --upgrade pip"
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.11.1
          pip install pillow==8.4.0
          pip install tweepy==4.6.0
          echo "::endgroup::"
          python -B ./news/news.py
      - name: commit&push
        run: |    # 差分が発生した場合のみcommit&push
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m 'Updated news.txt'; \
            git push origin HEAD:${GITHUB_REF}; \
            echo '# Updated news.txt :rocket:' >> $GITHUB_STEP_SUMMARY; \
          fi
